services:
  db:
    image: postgres:16-alpine
    container_name: recetario_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-recetario}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-recetario}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    container_name: recetario_backend
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://app:secret@db:5432/recetario}
      PORT: ${PORT:-3000}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    container_name: recetario_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data:
